import java.util.Arrays;
import java.util.HashMap;

public final class kq {
  public int a;
  
  public final nq b;
  
  public final mq c;
  
  public final lq d;
  
  public final oq e;
  
  public HashMap f;
  
  public kq() {
    Object object = new Object();
    ((nq)object).a = 0;
    ((nq)object).b = 0;
    ((nq)object).c = 1.0F;
    ((nq)object).d = Float.NaN;
    this.b = (nq)object;
    object = new Object();
    ((mq)object).a = -1;
    ((mq)object).b = 0;
    ((mq)object).c = -1;
    ((mq)object).d = Float.NaN;
    ((mq)object).e = Float.NaN;
    ((mq)object).f = Float.NaN;
    ((mq)object).g = -1;
    ((mq)object).h = null;
    ((mq)object).i = -1;
    this.c = (mq)object;
    object = new Object();
    ((lq)object).a = false;
    ((lq)object).d = -1;
    ((lq)object).e = -1;
    ((lq)object).f = -1.0F;
    ((lq)object).g = true;
    ((lq)object).h = -1;
    ((lq)object).i = -1;
    ((lq)object).j = -1;
    ((lq)object).k = -1;
    ((lq)object).l = -1;
    ((lq)object).m = -1;
    ((lq)object).n = -1;
    ((lq)object).o = -1;
    ((lq)object).p = -1;
    ((lq)object).q = -1;
    ((lq)object).r = -1;
    ((lq)object).s = -1;
    ((lq)object).t = -1;
    ((lq)object).u = -1;
    ((lq)object).v = -1;
    ((lq)object).w = 0.5F;
    ((lq)object).x = 0.5F;
    ((lq)object).y = null;
    ((lq)object).z = -1;
    ((lq)object).A = 0;
    ((lq)object).B = 0.0F;
    ((lq)object).C = -1;
    ((lq)object).D = -1;
    ((lq)object).E = -1;
    ((lq)object).F = 0;
    ((lq)object).G = 0;
    ((lq)object).H = 0;
    ((lq)object).I = 0;
    ((lq)object).J = 0;
    ((lq)object).K = 0;
    ((lq)object).L = 0;
    ((lq)object).M = Integer.MIN_VALUE;
    ((lq)object).N = Integer.MIN_VALUE;
    ((lq)object).O = Integer.MIN_VALUE;
    ((lq)object).P = Integer.MIN_VALUE;
    ((lq)object).Q = Integer.MIN_VALUE;
    ((lq)object).R = Integer.MIN_VALUE;
    ((lq)object).S = Integer.MIN_VALUE;
    ((lq)object).T = -1.0F;
    ((lq)object).U = -1.0F;
    ((lq)object).V = 0;
    ((lq)object).W = 0;
    ((lq)object).X = 0;
    ((lq)object).Y = 0;
    ((lq)object).Z = 0;
    ((lq)object).a0 = 0;
    ((lq)object).b0 = 0;
    ((lq)object).c0 = 0;
    ((lq)object).d0 = 1.0F;
    ((lq)object).e0 = 1.0F;
    ((lq)object).f0 = -1;
    ((lq)object).g0 = 0;
    ((lq)object).h0 = -1;
    ((lq)object).l0 = false;
    ((lq)object).m0 = false;
    ((lq)object).n0 = true;
    ((lq)object).o0 = 0;
    this.d = (lq)object;
    object = new Object();
    ((oq)object).a = 0.0F;
    ((oq)object).b = 0.0F;
    ((oq)object).c = 0.0F;
    ((oq)object).d = 1.0F;
    ((oq)object).e = 1.0F;
    ((oq)object).f = Float.NaN;
    ((oq)object).g = Float.NaN;
    ((oq)object).h = -1;
    ((oq)object).i = 0.0F;
    ((oq)object).j = 0.0F;
    ((oq)object).k = 0.0F;
    ((oq)object).l = false;
    ((oq)object).m = 0.0F;
    this.e = (oq)object;
    this.f = new HashMap<Object, Object>();
  }
  
  public final void a(gq paramgq) {
    lq lq1 = this.d;
    paramgq.e = lq1.h;
    paramgq.f = lq1.i;
    paramgq.g = lq1.j;
    paramgq.h = lq1.k;
    paramgq.i = lq1.l;
    paramgq.j = lq1.m;
    paramgq.k = lq1.n;
    paramgq.l = lq1.o;
    paramgq.m = lq1.p;
    paramgq.n = lq1.q;
    paramgq.o = lq1.r;
    paramgq.s = lq1.s;
    paramgq.t = lq1.t;
    paramgq.u = lq1.u;
    paramgq.v = lq1.v;
    paramgq.leftMargin = lq1.F;
    paramgq.rightMargin = lq1.G;
    paramgq.topMargin = lq1.H;
    paramgq.bottomMargin = lq1.I;
    paramgq.A = lq1.R;
    paramgq.B = lq1.Q;
    paramgq.x = lq1.N;
    paramgq.z = lq1.P;
    paramgq.E = lq1.w;
    paramgq.F = lq1.x;
    paramgq.p = lq1.z;
    paramgq.q = lq1.A;
    paramgq.r = lq1.B;
    paramgq.G = lq1.y;
    paramgq.T = lq1.C;
    paramgq.U = lq1.D;
    paramgq.I = lq1.T;
    paramgq.H = lq1.U;
    paramgq.K = lq1.W;
    paramgq.J = lq1.V;
    paramgq.W = lq1.l0;
    paramgq.X = lq1.m0;
    paramgq.L = lq1.X;
    paramgq.M = lq1.Y;
    paramgq.P = lq1.Z;
    paramgq.Q = lq1.a0;
    paramgq.N = lq1.b0;
    paramgq.O = lq1.c0;
    paramgq.R = lq1.d0;
    paramgq.S = lq1.e0;
    paramgq.V = lq1.E;
    paramgq.c = lq1.f;
    paramgq.a = lq1.d;
    paramgq.b = lq1.e;
    paramgq.width = lq1.b;
    paramgq.height = lq1.c;
    String str = lq1.k0;
    if (str != null)
      paramgq.Y = str; 
    paramgq.Z = lq1.o0;
    paramgq.setMarginStart(lq1.K);
    paramgq.setMarginEnd(lq1.J);
    paramgq.a();
  }
  
  public final Object clone() {
    kq kq1 = new kq();
    lq lq2 = kq1.d;
    lq2.getClass();
    lq lq1 = this.d;
    lq2.a = lq1.a;
    lq2.b = lq1.b;
    lq2.c = lq1.c;
    lq2.d = lq1.d;
    lq2.e = lq1.e;
    lq2.f = lq1.f;
    lq2.g = lq1.g;
    lq2.h = lq1.h;
    lq2.i = lq1.i;
    lq2.j = lq1.j;
    lq2.k = lq1.k;
    lq2.l = lq1.l;
    lq2.m = lq1.m;
    lq2.n = lq1.n;
    lq2.o = lq1.o;
    lq2.p = lq1.p;
    lq2.q = lq1.q;
    lq2.r = lq1.r;
    lq2.s = lq1.s;
    lq2.t = lq1.t;
    lq2.u = lq1.u;
    lq2.v = lq1.v;
    lq2.w = lq1.w;
    lq2.x = lq1.x;
    lq2.y = lq1.y;
    lq2.z = lq1.z;
    lq2.A = lq1.A;
    lq2.B = lq1.B;
    lq2.C = lq1.C;
    lq2.D = lq1.D;
    lq2.E = lq1.E;
    lq2.F = lq1.F;
    lq2.G = lq1.G;
    lq2.H = lq1.H;
    lq2.I = lq1.I;
    lq2.J = lq1.J;
    lq2.K = lq1.K;
    lq2.L = lq1.L;
    lq2.M = lq1.M;
    lq2.N = lq1.N;
    lq2.O = lq1.O;
    lq2.P = lq1.P;
    lq2.Q = lq1.Q;
    lq2.R = lq1.R;
    lq2.S = lq1.S;
    lq2.T = lq1.T;
    lq2.U = lq1.U;
    lq2.V = lq1.V;
    lq2.W = lq1.W;
    lq2.X = lq1.X;
    lq2.Y = lq1.Y;
    lq2.Z = lq1.Z;
    lq2.a0 = lq1.a0;
    lq2.b0 = lq1.b0;
    lq2.c0 = lq1.c0;
    lq2.d0 = lq1.d0;
    lq2.e0 = lq1.e0;
    lq2.f0 = lq1.f0;
    lq2.g0 = lq1.g0;
    lq2.h0 = lq1.h0;
    lq2.k0 = lq1.k0;
    int[] arrayOfInt = lq1.i0;
    if (arrayOfInt != null && lq1.j0 == null) {
      lq2.i0 = Arrays.copyOf(arrayOfInt, arrayOfInt.length);
    } else {
      lq2.i0 = null;
    } 
    lq2.j0 = lq1.j0;
    lq2.l0 = lq1.l0;
    lq2.m0 = lq1.m0;
    lq2.n0 = lq1.n0;
    lq2.o0 = lq1.o0;
    mq mq1 = kq1.c;
    mq1.getClass();
    mq mq2 = this.c;
    mq2.getClass();
    mq1.a = mq2.a;
    mq1.c = mq2.c;
    mq1.e = mq2.e;
    mq1.d = mq2.d;
    nq nq2 = this.b;
    int i = nq2.a;
    nq nq1 = kq1.b;
    nq1.a = i;
    nq1.c = nq2.c;
    nq1.d = nq2.d;
    nq1.b = nq2.b;
    oq oq1 = kq1.e;
    oq1.getClass();
    oq oq2 = this.e;
    oq2.getClass();
    oq1.a = oq2.a;
    oq1.b = oq2.b;
    oq1.c = oq2.c;
    oq1.d = oq2.d;
    oq1.e = oq2.e;
    oq1.f = oq2.f;
    oq1.g = oq2.g;
    oq1.h = oq2.h;
    oq1.i = oq2.i;
    oq1.j = oq2.j;
    oq1.k = oq2.k;
    oq1.l = oq2.l;
    oq1.m = oq2.m;
    kq1.a = this.a;
    return kq1;
  }
}


/* Location:              C:\Users\Kevin\Downloads\dex-tools-v2.4\dex-tools-v2.4\musicolet-dex2jar.jar!\kq.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */