package org.jaudiotagger.tag.reference;

import android.support.v4.graphics.drawable.uUq.IGBYXeDFmKYajx;
import android.window.ldG.XUaAMlaMSa;
import androidx.work.impl.diagnostics.UWhQ.OETETTfAjV;
import androidx.work.impl.utils.qnuS.eRUgfgGAccgka;
import com.android.billingclient.api.wH.DJqHMztxflt;
import com.google.android.gms.auth.api.signin.cwa.RqlokDsQOju;
import com.google.android.gms.cast.framework.internal.featurehighlight.aS.xveccWbRzqx;
import com.google.android.gms.common.api.Gldr.hbrAVtEa;
import com.google.android.gms.common.api.internal.jEVH.KjdXPYm;
import com.google.android.gms.common.internal.Qg.jHxlGgUTadw;
import com.google.android.gms.common.internal.Qg.nFLlOYeP;
import com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags.Ou.tlzLOCPTHRhep;
import com.google.android.material.tabs.xm.VDgS;
import com.sdsmdg.harjot.crollerTest.TG.ckOPp;
import in.krosbits.android.widgets.swipetoloadlayout.vZ.LHyji;
import in.krosbits.utils.SgV.YbNJ;
import in.krosbits.utils.SgV.zpEN;
import me.zhanghai.android.materialprogressbar.internal.pozR.kOkiWEITVb;
import org.jaudiotagger.audio.dff.vR.CKYHNesT;
import org.jaudiotagger.audio.dsf.qdA.GMDx;
import org.jaudiotagger.audio.exceptions.yb.zLtYiJUm;
import org.jaudiotagger.audio.opus.bsQ.uvJYmft;
import org.jaudiotagger.audio.real.Nq.JkpGFvCVQHzgc;
import org.jaudiotagger.tag.datatype.AbstractStringStringValuePair;
import org.jaudiotagger.tag.datatype.AbstractValuePair;
import org.jaudiotagger.tag.mp4.bKj.fXMDNeMWaILNVh;
import r3.IKWi.AyxAR;

public class Languages extends AbstractStringStringValuePair {
  public static final String DEFAULT_ID = "eng";
  
  public static final String DEFAULT_VALUE = "English";
  
  public static final int LANGUAGE_FIELD_SIZE = 3;
  
  public static final String MEDIA_MONKEY_ID = "XXX";
  
  public static final String WINAMP_ID = "\000\000\000";
  
  private static Languages languageTypes;
  
  private Languages() {
    ((AbstractValuePair)this).idToValue.put("aar", "Afar");
    ((AbstractValuePair)this).idToValue.put("abk", "Abkhazian");
    ((AbstractValuePair)this).idToValue.put("ace", "Achinese");
    ((AbstractValuePair)this).idToValue.put(ckOPp.vXb, "Acoli");
    ((AbstractValuePair)this).idToValue.put("ada", "Adangme");
    ((AbstractValuePair)this).idToValue.put("afa", "Afro-Asiatic");
    ((AbstractValuePair)this).idToValue.put("afh", "Afrihili");
    ((AbstractValuePair)this).idToValue.put("afr", "Afrikaans");
    ((AbstractValuePair)this).idToValue.put("aka", "Akan");
    ((AbstractValuePair)this).idToValue.put("akk", "Akkadian");
    ((AbstractValuePair)this).idToValue.put("alb", "Albanian");
    ((AbstractValuePair)this).idToValue.put("ale", "Aleut");
    ((AbstractValuePair)this).idToValue.put("alg", "Algonquian languages");
    ((AbstractValuePair)this).idToValue.put("amh", "Amharic");
    ((AbstractValuePair)this).idToValue.put("ang", "Old English,(ca.450-1100)");
    ((AbstractValuePair)this).idToValue.put("apa", eRUgfgGAccgka.ehRHvaVWjc);
    ((AbstractValuePair)this).idToValue.put("ara", "Arabic");
    ((AbstractValuePair)this).idToValue.put("arc", OETETTfAjV.tJLIyItC);
    ((AbstractValuePair)this).idToValue.put("arm", "Armenian");
    ((AbstractValuePair)this).idToValue.put("arn", "Araucanian");
    ((AbstractValuePair)this).idToValue.put("arp", "Arapaho");
    ((AbstractValuePair)this).idToValue.put("art", "Artificial");
    ((AbstractValuePair)this).idToValue.put("arw", "Arawak");
    ((AbstractValuePair)this).idToValue.put("asm", "Assamese");
    ((AbstractValuePair)this).idToValue.put("ast", "Asturian; Bable");
    ((AbstractValuePair)this).idToValue.put("ath", "Athapascan languages");
    ((AbstractValuePair)this).idToValue.put("aus", "Australian languages");
    ((AbstractValuePair)this).idToValue.put("ava", "Avaric");
    ((AbstractValuePair)this).idToValue.put("ave", "Avestan");
    ((AbstractValuePair)this).idToValue.put("awa", "Awadhi");
    ((AbstractValuePair)this).idToValue.put("aym", "Aymara");
    ((AbstractValuePair)this).idToValue.put("aze", "Azerbaijani");
    ((AbstractValuePair)this).idToValue.put("bad", "Banda");
    ((AbstractValuePair)this).idToValue.put("bai", "Bamileke languages");
    ((AbstractValuePair)this).idToValue.put("bak", "Bashkir");
    ((AbstractValuePair)this).idToValue.put("bal", "Baluchi");
    ((AbstractValuePair)this).idToValue.put("bam", "Bambara");
    ((AbstractValuePair)this).idToValue.put("ban", "Balinese");
    ((AbstractValuePair)this).idToValue.put("baq", "Basque");
    ((AbstractValuePair)this).idToValue.put("bas", "Basa");
    ((AbstractValuePair)this).idToValue.put("bat", "Baltic");
    ((AbstractValuePair)this).idToValue.put("bej", "Beja");
    ((AbstractValuePair)this).idToValue.put("bel", "Belarusian");
    ((AbstractValuePair)this).idToValue.put("bem", "Bemba");
    ((AbstractValuePair)this).idToValue.put("ben", fXMDNeMWaILNVh.PGT);
    ((AbstractValuePair)this).idToValue.put("ber", "Berber");
    ((AbstractValuePair)this).idToValue.put("bho", "Bhojpuri");
    ((AbstractValuePair)this).idToValue.put("bih", "Bihari");
    ((AbstractValuePair)this).idToValue.put("bik", "Bikol");
    ((AbstractValuePair)this).idToValue.put("bin", "Bini");
    ((AbstractValuePair)this).idToValue.put("bis", "Bislama");
    ((AbstractValuePair)this).idToValue.put("bla", tlzLOCPTHRhep.QuclCQ);
    ((AbstractValuePair)this).idToValue.put("bnt", "Bantu");
    ((AbstractValuePair)this).idToValue.put("bod", "Tibetan");
    ((AbstractValuePair)this).idToValue.put("bos", "Bosnian");
    ((AbstractValuePair)this).idToValue.put("bra", "Braj");
    ((AbstractValuePair)this).idToValue.put("bre", "Breton");
    ((AbstractValuePair)this).idToValue.put("btk", "Batak (Indonesia)");
    ((AbstractValuePair)this).idToValue.put("bua", "Buriat");
    ((AbstractValuePair)this).idToValue.put("bug", "Buginese");
    ((AbstractValuePair)this).idToValue.put("bul", "Bulgarian");
    ((AbstractValuePair)this).idToValue.put("bur", "Burmese");
    ((AbstractValuePair)this).idToValue.put("cad", "Caddo");
    ((AbstractValuePair)this).idToValue.put("cai", "Central American Indian");
    ((AbstractValuePair)this).idToValue.put("car", "Carib");
    ((AbstractValuePair)this).idToValue.put("cat", "Catalan");
    ((AbstractValuePair)this).idToValue.put("cau", "Caucasian");
    ((AbstractValuePair)this).idToValue.put("ceb", "Cebuano");
    ((AbstractValuePair)this).idToValue.put("cel", "Celtic");
    ((AbstractValuePair)this).idToValue.put("ces", "Czech");
    ((AbstractValuePair)this).idToValue.put("cha", "Chamorro");
    ((AbstractValuePair)this).idToValue.put("chb", "Chibcha");
    ((AbstractValuePair)this).idToValue.put("che", "Chechen");
    ((AbstractValuePair)this).idToValue.put("chg", "Chagatai");
    ((AbstractValuePair)this).idToValue.put("chi", "Chinese");
    ((AbstractValuePair)this).idToValue.put("chk", "Chuukese");
    ((AbstractValuePair)this).idToValue.put("chm", "Mari");
    ((AbstractValuePair)this).idToValue.put("chn", "Chinook jargon");
    ((AbstractValuePair)this).idToValue.put("cho", "Choctaw");
    ((AbstractValuePair)this).idToValue.put("chp", "Chipewyan");
    ((AbstractValuePair)this).idToValue.put("chr", YbNJ.AbFV);
    ((AbstractValuePair)this).idToValue.put("chu", "Church Slavic");
    ((AbstractValuePair)this).idToValue.put("chv", "Chuvash");
    ((AbstractValuePair)this).idToValue.put("chy", "Cheyenne");
    ((AbstractValuePair)this).idToValue.put("cmc", "Chamic languages");
    ((AbstractValuePair)this).idToValue.put("cop", "Coptic");
    ((AbstractValuePair)this).idToValue.put(LHyji.PYsnqhHLJJYqCRb, YbNJ.hQUvnJtWjeIKAGB);
    ((AbstractValuePair)this).idToValue.put("cos", uvJYmft.QanR);
    ((AbstractValuePair)this).idToValue.put("cpe", "Creoles and pidgins, English based");
    ((AbstractValuePair)this).idToValue.put("cpf", "Creoles and pidgins, French based");
    ((AbstractValuePair)this).idToValue.put("cpp", "Creoles and pidgins");
    ((AbstractValuePair)this).idToValue.put("cre", "Cree");
    ((AbstractValuePair)this).idToValue.put("crp", "Creoles and pidgins");
    ((AbstractValuePair)this).idToValue.put("cus", "Cushitic");
    ((AbstractValuePair)this).idToValue.put("cym", "Welsh");
    ((AbstractValuePair)this).idToValue.put("cze", "Czech");
    ((AbstractValuePair)this).idToValue.put("dak", "Dakota");
    ((AbstractValuePair)this).idToValue.put("dan", "Danish");
    ((AbstractValuePair)this).idToValue.put("day", "Dayak");
    ((AbstractValuePair)this).idToValue.put("del", "Delaware");
    ((AbstractValuePair)this).idToValue.put("den", "Slave (Athapascan)");
    ((AbstractValuePair)this).idToValue.put("deu", "German");
    ((AbstractValuePair)this).idToValue.put("dgr", "Dogrib");
    ((AbstractValuePair)this).idToValue.put("din", "Dinka");
    ((AbstractValuePair)this).idToValue.put("div", "Divehi");
    ((AbstractValuePair)this).idToValue.put("doi", "Dogri");
    ((AbstractValuePair)this).idToValue.put("dra", "Dravidian");
    ((AbstractValuePair)this).idToValue.put("dua", XUaAMlaMSa.fOhtpPfvdqIwyDL);
    ((AbstractValuePair)this).idToValue.put("dum", "Dutch, Middle (ca.1050-1350)");
    ((AbstractValuePair)this).idToValue.put("dut", "Dutch");
    ((AbstractValuePair)this).idToValue.put(zLtYiJUm.eVi, "Dyula");
    ((AbstractValuePair)this).idToValue.put("dzo", "Dzongkha");
    ((AbstractValuePair)this).idToValue.put("efi", "Efik");
    ((AbstractValuePair)this).idToValue.put("egy", "Egyptian (Ancient)");
    ((AbstractValuePair)this).idToValue.put("eka", "Ekajuk");
    ((AbstractValuePair)this).idToValue.put("ell", "Greek, Modern (1453-)");
    ((AbstractValuePair)this).idToValue.put("elx", "Elamite");
    ((AbstractValuePair)this).idToValue.put("eng", "English");
    ((AbstractValuePair)this).idToValue.put("enm", "English, Middle (1100-1500)");
    ((AbstractValuePair)this).idToValue.put("epo", "Esperanto");
    ((AbstractValuePair)this).idToValue.put("est", "Estonian");
    ((AbstractValuePair)this).idToValue.put("eus", "Basque");
    ((AbstractValuePair)this).idToValue.put("ewe", "Ewe");
    ((AbstractValuePair)this).idToValue.put("ewo", "Ewondo");
    ((AbstractValuePair)this).idToValue.put("fan", "Fang");
    ((AbstractValuePair)this).idToValue.put("fao", "Faroese");
    ((AbstractValuePair)this).idToValue.put("fas", "Persian");
    ((AbstractValuePair)this).idToValue.put(tlzLOCPTHRhep.GcoyCw, "Fanti");
    ((AbstractValuePair)this).idToValue.put("fij", "Fijian");
    ((AbstractValuePair)this).idToValue.put("fin", "Finnish");
    ((AbstractValuePair)this).idToValue.put("fiu", "Finno-Ugrian");
    ((AbstractValuePair)this).idToValue.put("fon", "Fon");
    ((AbstractValuePair)this).idToValue.put("fra", "French");
    ((AbstractValuePair)this).idToValue.put("frm", "French, Middle (ca.1400-1800)");
    ((AbstractValuePair)this).idToValue.put("fro", "French, Old (842-ca.1400)");
    ((AbstractValuePair)this).idToValue.put("fry", "Frisian");
    ((AbstractValuePair)this).idToValue.put("ful", "Fulah");
    ((AbstractValuePair)this).idToValue.put("fur", "Friulian");
    ((AbstractValuePair)this).idToValue.put("gaa", "Ga");
    ((AbstractValuePair)this).idToValue.put("gay", "Gayo");
    ((AbstractValuePair)this).idToValue.put("gba", "Gbaya");
    ((AbstractValuePair)this).idToValue.put("gem", "Germanic");
    ((AbstractValuePair)this).idToValue.put("geo", "Georgian");
    ((AbstractValuePair)this).idToValue.put(hbrAVtEa.INRNmyXkOfcep, "German");
    ((AbstractValuePair)this).idToValue.put("gez", "Geez");
    ((AbstractValuePair)this).idToValue.put("gil", "Gilbertese");
    ((AbstractValuePair)this).idToValue.put("gla", "Gaelic; Scottish Gaelic");
    ((AbstractValuePair)this).idToValue.put("gle", "Irish");
    ((AbstractValuePair)this).idToValue.put("glg", "Gallegan");
    ((AbstractValuePair)this).idToValue.put("glv", "Manx");
    ((AbstractValuePair)this).idToValue.put("gmh", "German, Middle High (ca.1050-1500)");
    ((AbstractValuePair)this).idToValue.put("goh", "German, Old High (ca.750-1050)");
    ((AbstractValuePair)this).idToValue.put("gon", "Gondi");
    ((AbstractValuePair)this).idToValue.put("gor", "Gorontalo");
    ((AbstractValuePair)this).idToValue.put("got", "Gothic");
    ((AbstractValuePair)this).idToValue.put("grb", "Grebo");
    ((AbstractValuePair)this).idToValue.put("grc", "Greek, Ancient (to 1453)");
    ((AbstractValuePair)this).idToValue.put(uvJYmft.dLfxbwWW, "Greek, Modern (1453-)");
    ((AbstractValuePair)this).idToValue.put("grn", "Guarani");
    ((AbstractValuePair)this).idToValue.put("guj", "Gujarati");
    ((AbstractValuePair)this).idToValue.put("gwi", "Gwich´in");
    ((AbstractValuePair)this).idToValue.put("hai", "Haida");
    ((AbstractValuePair)this).idToValue.put("hau", "Hausa");
    ((AbstractValuePair)this).idToValue.put("haw", "Hawaiian");
    ((AbstractValuePair)this).idToValue.put("heb", "Hebrew");
    ((AbstractValuePair)this).idToValue.put("her", "Herero");
    ((AbstractValuePair)this).idToValue.put("hil", "Hiligaynon");
    ((AbstractValuePair)this).idToValue.put("him", "Himachali");
    ((AbstractValuePair)this).idToValue.put("hin", "Hindi");
    ((AbstractValuePair)this).idToValue.put("hit", "Hittite");
    ((AbstractValuePair)this).idToValue.put("hmn", "Hmong");
    ((AbstractValuePair)this).idToValue.put("hmo", "Hiri Motu");
    ((AbstractValuePair)this).idToValue.put("hrv", "Croatian");
    ((AbstractValuePair)this).idToValue.put("hun", "Hungarian");
    ((AbstractValuePair)this).idToValue.put("hup", "Hupa");
    ((AbstractValuePair)this).idToValue.put("hye", "Armenian");
    ((AbstractValuePair)this).idToValue.put("iba", "Iban");
    ((AbstractValuePair)this).idToValue.put(VDgS.avv, "Igbo");
    ((AbstractValuePair)this).idToValue.put("ice", "Icelandic");
    ((AbstractValuePair)this).idToValue.put("ido", "Ido");
    ((AbstractValuePair)this).idToValue.put("ijo", "Ijo");
    ((AbstractValuePair)this).idToValue.put("iku", eRUgfgGAccgka.maMTRlygPrLJg);
    ((AbstractValuePair)this).idToValue.put("ile", "Interlingue");
    ((AbstractValuePair)this).idToValue.put("ilo", "Iloko");
    ((AbstractValuePair)this).idToValue.put("ina", "Interlingua");
    ((AbstractValuePair)this).idToValue.put(RqlokDsQOju.phyAoVxtHE, "Indic");
    ((AbstractValuePair)this).idToValue.put("ind", "Indonesian");
    ((AbstractValuePair)this).idToValue.put("ine", "Indo-European");
    ((AbstractValuePair)this).idToValue.put("ipk", "Inupiaq");
    ((AbstractValuePair)this).idToValue.put(ckOPp.gfZLY, "Iranian (Other)");
    ((AbstractValuePair)this).idToValue.put("iro", "Iroquoian languages");
    ((AbstractValuePair)this).idToValue.put("isl", "Icelandic");
    ((AbstractValuePair)this).idToValue.put("ita", "Italian");
    ((AbstractValuePair)this).idToValue.put("jav", uvJYmft.LzFavbpJIrS);
    ((AbstractValuePair)this).idToValue.put("jpn", "Japanese");
    ((AbstractValuePair)this).idToValue.put("jpr", "Judeo-Persian");
    ((AbstractValuePair)this).idToValue.put("jrb", jHxlGgUTadw.IwtLwRSTAcEuo);
    ((AbstractValuePair)this).idToValue.put("kaa", "Kara-Kalpak");
    ((AbstractValuePair)this).idToValue.put("kab", "Kabyle");
    ((AbstractValuePair)this).idToValue.put("kac", "Kachin");
    ((AbstractValuePair)this).idToValue.put("kal", "Kalaallisut");
    ((AbstractValuePair)this).idToValue.put("kam", "Kamba");
    ((AbstractValuePair)this).idToValue.put("kan", "Kannada");
    ((AbstractValuePair)this).idToValue.put("kar", "Karen");
    ((AbstractValuePair)this).idToValue.put("kas", "Kashmiri");
    ((AbstractValuePair)this).idToValue.put("kat", "Georgian");
    ((AbstractValuePair)this).idToValue.put("kau", "Kanuri");
    ((AbstractValuePair)this).idToValue.put("kaw", "Kawi");
    ((AbstractValuePair)this).idToValue.put("kaz", "Kazakh");
    ((AbstractValuePair)this).idToValue.put("kha", "Khasi");
    ((AbstractValuePair)this).idToValue.put("khi", "Khoisan");
    ((AbstractValuePair)this).idToValue.put("khm", jHxlGgUTadw.hSYvORUi);
    ((AbstractValuePair)this).idToValue.put("kho", "Khotanese");
    ((AbstractValuePair)this).idToValue.put("kik", "Kikuyu; Gikuyu");
    ((AbstractValuePair)this).idToValue.put("kin", "Kinyarwanda");
    ((AbstractValuePair)this).idToValue.put("kir", "Kirghiz");
    ((AbstractValuePair)this).idToValue.put("kmb", "Kimbundu");
    ((AbstractValuePair)this).idToValue.put("kok", "Konkani");
    ((AbstractValuePair)this).idToValue.put("kom", "Komi");
    ((AbstractValuePair)this).idToValue.put("kon", "Kongo");
    ((AbstractValuePair)this).idToValue.put("kor", kOkiWEITVb.kEZtOl);
    ((AbstractValuePair)this).idToValue.put("kos", fXMDNeMWaILNVh.VcJNAl);
    ((AbstractValuePair)this).idToValue.put("kpe", "Kpelle");
    ((AbstractValuePair)this).idToValue.put("kro", "Kru");
    ((AbstractValuePair)this).idToValue.put("kru", "Kurukh");
    ((AbstractValuePair)this).idToValue.put("kua", "Kuanyama; Kwanyama");
    ((AbstractValuePair)this).idToValue.put("kum", "Kumyk");
    ((AbstractValuePair)this).idToValue.put("kur", "Kurdish");
    ((AbstractValuePair)this).idToValue.put("kut", "Kutenai");
    ((AbstractValuePair)this).idToValue.put("lad", "Ladino");
    ((AbstractValuePair)this).idToValue.put("lah", "Lahnda");
    ((AbstractValuePair)this).idToValue.put("lam", "Lamba");
    ((AbstractValuePair)this).idToValue.put("lao", "Lao");
    ((AbstractValuePair)this).idToValue.put("lat", "Latin");
    ((AbstractValuePair)this).idToValue.put("lav", "Latvian");
    ((AbstractValuePair)this).idToValue.put("lez", "Lezghian");
    ((AbstractValuePair)this).idToValue.put("lin", "Lingala");
    ((AbstractValuePair)this).idToValue.put("lit", "Lithuanian");
    ((AbstractValuePair)this).idToValue.put("lol", "Mongo");
    ((AbstractValuePair)this).idToValue.put("loz", "Lozi");
    ((AbstractValuePair)this).idToValue.put("ltz", "Luxembourgish; Letzeburgesch");
    ((AbstractValuePair)this).idToValue.put("lua", "Luba-Lulua");
    ((AbstractValuePair)this).idToValue.put("lub", "Luba-Katanga");
    ((AbstractValuePair)this).idToValue.put("lug", JkpGFvCVQHzgc.VYWb);
    ((AbstractValuePair)this).idToValue.put("lui", "Luiseno");
    ((AbstractValuePair)this).idToValue.put("lun", "Lunda");
    ((AbstractValuePair)this).idToValue.put("luo", "Luo (Kenya and Tanzania)");
    ((AbstractValuePair)this).idToValue.put("lus", "lushai");
    ((AbstractValuePair)this).idToValue.put("mac", "Macedonian");
    ((AbstractValuePair)this).idToValue.put("mad", "Madurese");
    ((AbstractValuePair)this).idToValue.put("mag", "Magahi");
    ((AbstractValuePair)this).idToValue.put("mah", "Marshallese");
    ((AbstractValuePair)this).idToValue.put("mai", "Maithili");
    ((AbstractValuePair)this).idToValue.put("mak", "Makasar");
    ((AbstractValuePair)this).idToValue.put("mal", "Malayalam");
    ((AbstractValuePair)this).idToValue.put("man", hbrAVtEa.HuYwWipC);
    ((AbstractValuePair)this).idToValue.put("mao", "Maori");
    ((AbstractValuePair)this).idToValue.put("map", "Austronesian");
    ((AbstractValuePair)this).idToValue.put("mar", "Marathi");
    ((AbstractValuePair)this).idToValue.put("mas", "Masai");
    ((AbstractValuePair)this).idToValue.put("may", "Malay");
    ((AbstractValuePair)this).idToValue.put("mdr", "Mandar");
    ((AbstractValuePair)this).idToValue.put("men", "Mende");
    ((AbstractValuePair)this).idToValue.put("mga", "Irish, Middle (900-1200)");
    ((AbstractValuePair)this).idToValue.put("mic", "Micmac");
    ((AbstractValuePair)this).idToValue.put("min", "Minangkabau");
    ((AbstractValuePair)this).idToValue.put("mis", "Miscellaneous languages");
    ((AbstractValuePair)this).idToValue.put("mkd", "Macedonian");
    ((AbstractValuePair)this).idToValue.put("mkh", "Mon-Khmer");
    ((AbstractValuePair)this).idToValue.put("mlg", "Malagasy");
    ((AbstractValuePair)this).idToValue.put("mlt", OETETTfAjV.scPjgOadwyFHizh);
    ((AbstractValuePair)this).idToValue.put("mnc", "Manchu");
    ((AbstractValuePair)this).idToValue.put("mni", "Manipuri");
    ((AbstractValuePair)this).idToValue.put("mno", "Manobo languages");
    ((AbstractValuePair)this).idToValue.put("moh", "Mohawk");
    ((AbstractValuePair)this).idToValue.put("mol", "Moldavian");
    ((AbstractValuePair)this).idToValue.put("mon", "Mongolian");
    ((AbstractValuePair)this).idToValue.put("mos", "Mossi");
    ((AbstractValuePair)this).idToValue.put("mri", "Maori");
    ((AbstractValuePair)this).idToValue.put("msa", "Malay");
    ((AbstractValuePair)this).idToValue.put("mul", "Multiple languages");
    ((AbstractValuePair)this).idToValue.put("mun", "Munda languages");
    ((AbstractValuePair)this).idToValue.put("mus", fXMDNeMWaILNVh.hPLyycVFHOVK);
    ((AbstractValuePair)this).idToValue.put("mwr", "Marwari");
    ((AbstractValuePair)this).idToValue.put("mya", "Burmese");
    ((AbstractValuePair)this).idToValue.put("myn", "Mayan languages");
    ((AbstractValuePair)this).idToValue.put("nah", "Nahuatl");
    ((AbstractValuePair)this).idToValue.put("nai", "North American Indian");
    ((AbstractValuePair)this).idToValue.put("nau", "Nauru");
    ((AbstractValuePair)this).idToValue.put(nFLlOYeP.WjEvfKFZ, "Navajo; Navaho");
    ((AbstractValuePair)this).idToValue.put("nbl", "South Ndebele");
    ((AbstractValuePair)this).idToValue.put("nde", "North Ndebele");
    ((AbstractValuePair)this).idToValue.put("ndo", "Ndonga");
    ((AbstractValuePair)this).idToValue.put("nds", "Low German; Low Saxon");
    ((AbstractValuePair)this).idToValue.put(xveccWbRzqx.NCpCPsZzfLqa, "Nepali");
    ((AbstractValuePair)this).idToValue.put("new", "Newari");
    ((AbstractValuePair)this).idToValue.put("nia", "Nias");
    ((AbstractValuePair)this).idToValue.put("nic", "Niger-Kordofanian");
    ((AbstractValuePair)this).idToValue.put("niu", jHxlGgUTadw.oudPDejLy);
    ((AbstractValuePair)this).idToValue.put("nld", "Dutch");
    ((AbstractValuePair)this).idToValue.put("nno", "Norwegian Nynorsk");
    ((AbstractValuePair)this).idToValue.put("nob", "Norwegian Bokmål");
    ((AbstractValuePair)this).idToValue.put("non", "Norse, Old");
    ((AbstractValuePair)this).idToValue.put("nor", "Norwegian");
    ((AbstractValuePair)this).idToValue.put("nso", "Sotho, Northern");
    ((AbstractValuePair)this).idToValue.put("nub", "Nubian languages");
    ((AbstractValuePair)this).idToValue.put("nya", "Chichewa; Chewa; Nyanja");
    ((AbstractValuePair)this).idToValue.put("nym", "Nyamwezi");
    ((AbstractValuePair)this).idToValue.put("nyn", "Nyankole");
    ((AbstractValuePair)this).idToValue.put("nyo", "Nyoro");
    ((AbstractValuePair)this).idToValue.put("nzi", "Nzima");
    ((AbstractValuePair)this).idToValue.put("oci", "Occitan (post 1500); Provençal");
    ((AbstractValuePair)this).idToValue.put("oji", "Ojibwa");
    ((AbstractValuePair)this).idToValue.put("ori", "Oriya");
    ((AbstractValuePair)this).idToValue.put("orm", "Oromo");
    ((AbstractValuePair)this).idToValue.put("osa", "Osage");
    ((AbstractValuePair)this).idToValue.put("oss", "Ossetian; Ossetic");
    ((AbstractValuePair)this).idToValue.put("ota", "Turkish, Ottoman (1500-1928)");
    ((AbstractValuePair)this).idToValue.put("oto", "Otomian languages");
    ((AbstractValuePair)this).idToValue.put("paa", "Papuan");
    ((AbstractValuePair)this).idToValue.put("pag", "Pangasinan");
    ((AbstractValuePair)this).idToValue.put("pal", "Pahlavi");
    ((AbstractValuePair)this).idToValue.put("pam", "Pampanga");
    ((AbstractValuePair)this).idToValue.put("pan", "Panjabi");
    ((AbstractValuePair)this).idToValue.put("pap", "Papiamento");
    ((AbstractValuePair)this).idToValue.put("pau", "Palauan");
    ((AbstractValuePair)this).idToValue.put(AyxAR.SkNkQhnsaoXgfh, "Persian, Old (ca.600-400 B.C.)");
    ((AbstractValuePair)this).idToValue.put("per", "Persian");
    ((AbstractValuePair)this).idToValue.put("per", "Persian");
    ((AbstractValuePair)this).idToValue.put("phi", "Philippine");
    ((AbstractValuePair)this).idToValue.put("phn", "Phoenician");
    ((AbstractValuePair)this).idToValue.put("pli", "Pali");
    ((AbstractValuePair)this).idToValue.put("pol", "Polish");
    ((AbstractValuePair)this).idToValue.put("pon", "Pohnpeian");
    ((AbstractValuePair)this).idToValue.put("por", "Portuguese");
    ((AbstractValuePair)this).idToValue.put("pra", "Prakrit languages");
    ((AbstractValuePair)this).idToValue.put("pro", "Provençal, Old (to 1500)");
    ((AbstractValuePair)this).idToValue.put("pus", "Pushto");
    ((AbstractValuePair)this).idToValue.put("que", "Quechua");
    ((AbstractValuePair)this).idToValue.put("raj", "Rajasthani");
    ((AbstractValuePair)this).idToValue.put("rap", "Rapanui");
    ((AbstractValuePair)this).idToValue.put("rar", "Rarotongan");
    ((AbstractValuePair)this).idToValue.put("roa", "Romance");
    ((AbstractValuePair)this).idToValue.put("roh", "Raeto-Romance");
    ((AbstractValuePair)this).idToValue.put("rom", "Romany");
    ((AbstractValuePair)this).idToValue.put("ron", "Romanian");
    ((AbstractValuePair)this).idToValue.put("rum", "Romanian");
    ((AbstractValuePair)this).idToValue.put("run", "Rundi");
    ((AbstractValuePair)this).idToValue.put("rus", "Russian");
    ((AbstractValuePair)this).idToValue.put("sad", "Sandawe");
    ((AbstractValuePair)this).idToValue.put("sag", "Sango");
    ((AbstractValuePair)this).idToValue.put("sah", "Yakut");
    ((AbstractValuePair)this).idToValue.put("sai", "South American Indian");
    ((AbstractValuePair)this).idToValue.put("sal", "Salishan languages");
    ((AbstractValuePair)this).idToValue.put("sam", "Samaritan Aramaic");
    ((AbstractValuePair)this).idToValue.put("san", "Sanskrit");
    ((AbstractValuePair)this).idToValue.put(KjdXPYm.GzqcyKiCiei, "Sasak");
    ((AbstractValuePair)this).idToValue.put("sat", "Santali");
    ((AbstractValuePair)this).idToValue.put("scc", "Serbian");
    ((AbstractValuePair)this).idToValue.put("sco", "Scots");
    ((AbstractValuePair)this).idToValue.put("scr", "Croatian");
    ((AbstractValuePair)this).idToValue.put("sel", "Selkup");
    ((AbstractValuePair)this).idToValue.put("sem", "Semitic");
    ((AbstractValuePair)this).idToValue.put(CKYHNesT.RcAPWffXqQtoM, "Irish, Old (to 900)");
    ((AbstractValuePair)this).idToValue.put("sgn", "Sign languages");
    ((AbstractValuePair)this).idToValue.put(hbrAVtEa.KpINzaOJttXGQym, zpEN.shoEOZCNB);
    ((AbstractValuePair)this).idToValue.put("sid", "Sidamo");
    ((AbstractValuePair)this).idToValue.put("sin", "Sinhales");
    ((AbstractValuePair)this).idToValue.put("sio", "Siouan languages");
    ((AbstractValuePair)this).idToValue.put("sit", "Sino-Tibetan");
    ((AbstractValuePair)this).idToValue.put("sla", "Slavic");
    ((AbstractValuePair)this).idToValue.put("slk", "Slovak");
    ((AbstractValuePair)this).idToValue.put("slo", "Slovak");
    ((AbstractValuePair)this).idToValue.put("slv", "Slovenian");
    ((AbstractValuePair)this).idToValue.put("sma", "Southern Sami");
    ((AbstractValuePair)this).idToValue.put("sme", "Northern Sami");
    ((AbstractValuePair)this).idToValue.put("smi", "Sami languages");
    ((AbstractValuePair)this).idToValue.put("smj", "Lule Sami");
    ((AbstractValuePair)this).idToValue.put("smn", "Inari Sami");
    ((AbstractValuePair)this).idToValue.put("smo", "Samoan");
    ((AbstractValuePair)this).idToValue.put("sms", "Skolt Sami");
    ((AbstractValuePair)this).idToValue.put("sna", "Shona");
    ((AbstractValuePair)this).idToValue.put("snd", "Sindhi");
    ((AbstractValuePair)this).idToValue.put("snk", "Soninke");
    ((AbstractValuePair)this).idToValue.put("sog", "Sogdian");
    ((AbstractValuePair)this).idToValue.put("som", "Somali");
    ((AbstractValuePair)this).idToValue.put("son", "Songhai");
    ((AbstractValuePair)this).idToValue.put("sot", "Sotho, Southern");
    ((AbstractValuePair)this).idToValue.put("spa", "Spanish; Castilia");
    ((AbstractValuePair)this).idToValue.put("sqi", "Albanian");
    ((AbstractValuePair)this).idToValue.put("srd", "Sardinian");
    ((AbstractValuePair)this).idToValue.put("srp", "Serbian");
    ((AbstractValuePair)this).idToValue.put("srr", "Serer");
    ((AbstractValuePair)this).idToValue.put("ssa", "Nilo-Saharan");
    ((AbstractValuePair)this).idToValue.put("sus", "Susu");
    ((AbstractValuePair)this).idToValue.put("sux", "Sumerian");
    ((AbstractValuePair)this).idToValue.put("swa", "Swahili");
    ((AbstractValuePair)this).idToValue.put("swe", "Swedish");
    ((AbstractValuePair)this).idToValue.put("syr", eRUgfgGAccgka.raRDIbnyrhWSX);
    ((AbstractValuePair)this).idToValue.put("tah", "Tahitian");
    ((AbstractValuePair)this).idToValue.put("tai", "Tai");
    ((AbstractValuePair)this).idToValue.put("tam", "Tamil");
    ((AbstractValuePair)this).idToValue.put("tat", "Tatar");
    ((AbstractValuePair)this).idToValue.put("tel", "Telugu");
    ((AbstractValuePair)this).idToValue.put("tem", "Timne");
    ((AbstractValuePair)this).idToValue.put("ter", "Tereno");
    ((AbstractValuePair)this).idToValue.put("tet", "Tetum");
    ((AbstractValuePair)this).idToValue.put("tgk", "Tajik");
    ((AbstractValuePair)this).idToValue.put("tgl", "Tagalog");
    ((AbstractValuePair)this).idToValue.put("tha", "Thai");
    ((AbstractValuePair)this).idToValue.put("tib", "Tibetan");
    ((AbstractValuePair)this).idToValue.put("tig", "Tigre");
    ((AbstractValuePair)this).idToValue.put("tir", "Tigrinya");
    ((AbstractValuePair)this).idToValue.put("tiv", "Tiv");
    ((AbstractValuePair)this).idToValue.put("tkl", "Tokelau");
    ((AbstractValuePair)this).idToValue.put("tli", "Tlingit");
    ((AbstractValuePair)this).idToValue.put("tmh", "Tamashek");
    ((AbstractValuePair)this).idToValue.put("tog", "Tonga (Nyasa)");
    ((AbstractValuePair)this).idToValue.put("ton", "Tonga (Tonga Islands)");
    ((AbstractValuePair)this).idToValue.put("tpi", "Tok Pisin");
    ((AbstractValuePair)this).idToValue.put("tsi", "Tsimshian");
    ((AbstractValuePair)this).idToValue.put("tsn", "Tswana");
    ((AbstractValuePair)this).idToValue.put("tso", "Tsonga");
    ((AbstractValuePair)this).idToValue.put("tuk", "Turkmen");
    ((AbstractValuePair)this).idToValue.put(LHyji.pjY, "Tumbuka");
    ((AbstractValuePair)this).idToValue.put("tup", "Tupi");
    ((AbstractValuePair)this).idToValue.put("tur", "Turkish");
    ((AbstractValuePair)this).idToValue.put("tut", "Altaic");
    ((AbstractValuePair)this).idToValue.put("tvl", "Tuvalu");
    ((AbstractValuePair)this).idToValue.put("twi", "Twi");
    ((AbstractValuePair)this).idToValue.put("tyv", "Tuvinian");
    ((AbstractValuePair)this).idToValue.put("uga", "Ugaritic");
    ((AbstractValuePair)this).idToValue.put("uig", "Uighur");
    ((AbstractValuePair)this).idToValue.put(GMDx.MzGrjhS, "Ukrainian");
    ((AbstractValuePair)this).idToValue.put("umb", "Umbundu");
    ((AbstractValuePair)this).idToValue.put("und", "Undetermined");
    ((AbstractValuePair)this).idToValue.put("urd", "Urdu");
    ((AbstractValuePair)this).idToValue.put("uzb", "Uzbek");
    ((AbstractValuePair)this).idToValue.put("vai", "Vai");
    ((AbstractValuePair)this).idToValue.put("ven", "Venda");
    ((AbstractValuePair)this).idToValue.put(VDgS.WZGRvxRMs, DJqHMztxflt.UNcu);
    ((AbstractValuePair)this).idToValue.put("vol", "Volapük");
    ((AbstractValuePair)this).idToValue.put("vot", "Votic");
    ((AbstractValuePair)this).idToValue.put("wak", CKYHNesT.HLo);
    ((AbstractValuePair)this).idToValue.put("wal", "Walamo");
    ((AbstractValuePair)this).idToValue.put("war", "Waray");
    ((AbstractValuePair)this).idToValue.put("was", "Washo");
    ((AbstractValuePair)this).idToValue.put("wel", "Welsh");
    ((AbstractValuePair)this).idToValue.put("wen", "Sorbian languages");
    ((AbstractValuePair)this).idToValue.put("wln", "Walloon");
    ((AbstractValuePair)this).idToValue.put("wol", "Wolof");
    ((AbstractValuePair)this).idToValue.put("xho", "Xhosa");
    ((AbstractValuePair)this).idToValue.put(AyxAR.RzikGWYDvwwxYog, "Yao");
    ((AbstractValuePair)this).idToValue.put("yap", "Yapese");
    ((AbstractValuePair)this).idToValue.put("yid", "Yiddish");
    ((AbstractValuePair)this).idToValue.put("yor", "Yoruba");
    ((AbstractValuePair)this).idToValue.put("ypk", "Yupik languages");
    ((AbstractValuePair)this).idToValue.put("zap", "Zapotec");
    ((AbstractValuePair)this).idToValue.put("zen", "Zenaga");
    ((AbstractValuePair)this).idToValue.put("zha", "Zhuang; Chuang");
    ((AbstractValuePair)this).idToValue.put("zho", "Chinese");
    ((AbstractValuePair)this).idToValue.put("znd", "Zande");
    ((AbstractValuePair)this).idToValue.put("zul", "Zulu");
    ((AbstractValuePair)this).idToValue.put(RqlokDsQOju.nebXZoy, IGBYXeDFmKYajx.EgDNo);
    ((AbstractValuePair)this).idToValue.put("\000\000\000", "Winamp Format");
    ((AbstractValuePair)this).idToValue.put("XXX", "Media Monkey Format");
    createMaps();
  }
  
  public static Languages getInstanceOf() {
    if (languageTypes == null)
      languageTypes = new Languages(); 
    return languageTypes;
  }
}


/* Location:              C:\Users\Kevin\Downloads\dex-tools-v2.4\dex-tools-v2.4\musicolet-dex2jar.jar!\org\jaudiotagger\tag\reference\Languages.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */